site_name: Xumes
theme: readthedocs
site_description: Xumes is a game testing tool for games
site_author: Xumes

nav:
  - User guide:
      - "Installation": 'usage.md'
      - "Getting started": 'description.md'
      - "CLI": 'cli.md'
  - Testers:
      - "Steps files": 'steps.md'
      - "Features files": 'features.md'
  - Trainers:
      - "Trainers files": 'trainers.md'
  - Documentation:
      - "Architecture": 'architecture.md'

