site_name: Xumes
theme: readthedocs

nav:
  - User guide:
      - "Installation": 'usage.md'
      - "Getting started": 'description.md'
      - "CLI": 'cli.md'
  - Testers guide:
      - "Steps files": 'steps.md'
      - "Features files": 'features.md'
  - Trainers guide:
      - "Trainers files": 'trainers.md'

