site_name: Xumes
theme: readthedocs

nav:
  - User guide:
      - "Installation": 'usage.md'
      - "Getting started": 'description.md'
  - Tester:
      - "Steps files": 'steps.md'
      - ".feature files": 'features.md'
      - "Start tester": 'start_tester.md'
      - "Trainers files": 'trainers.md'
      - "CLI": 'cli.md'
