site_name: Xumes
theme: readthedocs

nav:
  - User guide:
      - "Installation": 'usage.md'
      - "Getting started": 'description.md'
      - "Steps files": 'steps.md'
      - ".feature files": 'feature.md'
      - "Trainers files": 'trainers.md'
      - "CLI": 'cli.md'
