from xumes.game_module.implementations.rest_impl.communication_service_game_rest_api import CommunicationServiceGameRestApi
from xumes.game_module.implementations.rest_impl.json_game_state_observer import JsonGameStateObserver
from xumes.game_module.implementations.rest_impl.communication_service_test_manager_rest_api import CommunicationServiceTestManagerRestApi
